[monitoring_server]
monitoring ansible_host=192.168.56.10 ansible_user=wandji wg_ip=10.8.0.1

[managed_nodes]
node1 ansible_host=192.168.56.11 ansible_user=verra wg_ip=10.8.0.2

[all:vars]
lan_cidr=192.168.56.0/24
